apiVersion: apps/v1
kind: Deployment
metadata:
  name: ilightproj-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ilightproj-app
  template:
    metadata:
      labels:
        app: ilightproj-app
    spec:
      containers:
      - name: ilightproj-app
        image: docker.io/library/ilightproj-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ilightproj-service
spec:
  selector:
    app: ilightproj-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30462
  type: NodePort