apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-server
  template:
    metadata:
      labels:
        app: nodejs-server
    spec:
      containers:
        - name: nodejs-server
          image: crissvictor/ilight-server
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-server-service
spec:
  type: NodePort
  selector:
    app: nodejs-server
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30001 # Change if this port is used
